version: '2'
services:
  im-bot:
    image: cloudvalley/im-bot
    container_name: im-bot
    network_mode: 'container:coolq-server'
    volumes:
      - ./data/im-bot:/data
      - /tmp:/tmp
    environment:
      - TURING123_API_KEY=YOUR_API_KEY
      - HOST=0.0.0.0
      - PORT=8888
      - BAIDU_FANYI_APP_ID=YOUR_APP_ID
      - BAIDU_FANYI_API_KEY=YOUR_API_KEY
      - SPEECH_RECOGNITION_SERVICE=baidu|bing
      - BAIDU_SPEECH_API_KEY=YOUR_API_KEY
      - BAIDU_SPEECH_SECRET_KEY=YOUR_SECRET_KEY
      - BING_SPEECH_API_KEY=YOUR_API_KEY
      - HEWEATHER_API_KEY=YOUR_API_KEY
    restart: always